[tox]
min_version = 4.0
requires = tox-uv
envlist =
    py{310,311,312,313,314}

[testenv]
package = wheel
runner = uv-venv-runner
dependency_groups = test
setenv =
    COVERAGE_FILE = .coverage.{envname}

deps =
    mongoengine @ git+https://github.com/strollby/mongoengine@v0.30.0-alpha.3

commands =
    pytest --cov-report= --cov=graphene_mongo tests/ {posargs}