name: CI

on:
  pull_request:
  push:
    branches: ["develop", "master"]
  workflow_dispatch:

env:
  MAIN_PYTHON_VERSION: "3.14"

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v8
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
      - name: Run ruff
        run: uv run --with ruff ruff check .

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        mongodb-version: ["4.4", "5.0", "6.0", "7.0", "8.0" ]
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v8
        with:
          python-version: ${{ matrix.python-version }}
      - name: Start MongoDB ${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - name: Run tests
        run: |
          uv run --with tox --with tox-uv tox -e py$(echo "${{ matrix.python-version }}" | tr -d .)

  build:
    runs-on: ubuntu-latest
    needs: [linting, test]
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v8
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
      - name: Build wheel
        run: uv build